### ISSUE TITLE
Documentation refresh

### ISSUE THREAD

**Issue by slawekjaranowski** [mojohaus/javacc-maven-plugin#22]
Plugin documentation should be refreshed.
There are many broken links like: http://javacc.dev.java.net/

To verify: 
 - checkut project
 - run `mvn verify`
 - run `mvn site`
- examine generated documentation in `target/site/`

**Comment by olamy** [comment]
new site looks to be here https://javacc.github.io/javacc/

**Comment by zosrothko** [comment]
Hi

For your information, the JavaCC organisation made a fork of the 
javacc-maven-plugin to manage the new design of JavaCC 8 version, which 
is split into 1 core module and 4 code generators.

Here the project: https://github.com/javacc/javacc-maven-plugin with a 
changed artifact as _org.javacc.plugin:javacc-maven-plugin:3.0.4-SNAPSHOT_

_Rgds
_


Le 03/08/2022 à 03:03, Olivier Lamy a écrit :

**Comment by olamy** [comment]
@zosrothko why not participating here?

**Comment by zosrothko** [comment]
Because the mojohaus javacc-maven-plugin cannot support the new javacc-8 design. Javacc-8 is provding basically 2 jars. The core artifact -- the JavaCC grammar parser -- and a second one, the code generator (one of cpp, java, csharp or js generator). There is only one dependency from the code generator to the core. Hence the mojohaux javacc-maven-plugin cannot support this dynamic dependency since the version of javacc is fixed with only a sigle artifact. Please have a look to the Integration test of javacc-8 where the Javacc javacc-maven-plugin is use intensively. Plase follow those [steps ](https://github.com/javacc/javacc-8/discussions/2) to get the javacc-8 project

**Comment by olamy** [comment]
> Because the mojohaus javacc-maven-plugin cannot support the new javacc-8 design. Javacc-8 is provding basically 2 jars. The core artifact -- the JavaCC grammar parser -- and a second one, the code generator (one of cpp, java, csharp or js generator). There is only one dependency from the code generator to the core. Hence the mojohaux javacc-maven-plugin cannot support this dynamic dependency since the version of javacc is fixed with only a sigle artifact. Please have a look to the Integration test of javacc-8 where the Javacc javacc-maven-plugin is use intensively. Plase follow those [steps ](https://github.com/javacc/javacc-8/discussions/2) to get the javacc-8 project

fair enough....
but I'm pretty sure there are room for improvement here if you want to participate.....
